name: Mirror and run GitLab CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.kit.edu/keshvi.tuteja2/testing_ci_cd.git"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "keshvi.tuteja2"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN_MIRROR }}
        GITLAB_PROJECT_ID: "175011" 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
