name: Trigger GitLab CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  trigger_gitlab_ci:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger GitLab Pipeline
      id: trigger
      env:
        AUTHOR: ${{ github.event.pull_request.assignee.login }}
        BRANCH: ${{ github.head_ref }}
        SHA: ${{ github.sha }}
        PR_NUMBER: ${{ github.event.pull_request.number }}      
      run: |
        branch=${{ github.head_ref || github.ref_name }}
        response=$(curl -s -X POST -H "Content-Type: application/json" \
          -d "{\"ref\":\"refs/heads/main\"}" \
          -F "variables[SHA]=$SHA" \
          -F "variables[SHORT_SHA]=${SHORT_SHA}" \
          -F "variables[BRANCH]=$BRANCH" \
          -F "variables[PR]=$PR_NUMBER" \       
          "https://gitlab.kit.edu/api/v4/projects/175208/trigger/pipeline?token=${{ secrets.GITLAB_TOKEN }}")
        echo "Response: $response"
        pipeline_id=$(echo $response | jq -r '.id')
        pipeline_url=$(echo $response | jq -r '.web_url')
        if [ "$pipeline_id" == "null" ]; then
          echo "Pipeline ID is null. Check the response for errors."
          exit 1
        fi
        echo "PIPELINE_ID=$pipeline_id" >> $GITHUB_ENV
        echo "PIPELINE_URL=$pipeline_url" >> $GITHUB_ENV        



