name: mirror_repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  mirror_repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Mirror repository
      uses: yesolutions/mirror-action@v0.7.0
      with:
        REMOTE_NAME: pyGinkgo_mirror
        REMOTE: https://gitlab.kit.edu/keshvi.tuteja2/pyGinkgo.git
        GIT_USERNAME: keshvi.tuteja2
        GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN_MIRROR }}
